ci: move docker build image to custom ci image

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -50,35 +50,46 @@ stages:
         coverage_format: cobertura
         path: coverage.xml
 
-publish:docker:ci:
-  stage: pre
+.docker:
   variables:
     DOCKER_HOST: tcp://docker:2375
     DOCKER_DRIVER: overlay2
     DOCKER_TLS_CERTDIR: ""
-    IMAGE: $CI_REGISTRY_IMAGE/ci
+    IMMUTABLE: "true"
+  services:
+    - docker:27-dind
+  before_script:
+    - echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf
+    - nix-env -iA nixpkgs.docker
+    - |
+      if [ "$IMMUTABLE" = "true" ]; then
+        if docker pull $IMAGE; then
+          echo "Image with tag $IMAGE_TAG already exists. Failing the pipeline."
+          exit 1
+        fi
+      fi
+  script:
+    - nix build .#${FLAKE_TARGET}
+    - docker load < ./result
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+    # INFO: Check if the image tag already exists, until immutable tags are ready.
+    - docker image tag $LOCAL_IMAGE:latest $IMAGE
+    - docker push $IMAGE
+
+publish:docker:ci:
+  stage: pre
+  variables:
+    IMAGE: $BANTERBUS_CI_IMAGE
+    FLAKE_TARGET: container-ci
+    LOCAL_IMAGE: banterbus-dev
   rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
       changes:
         - "containers/ci.nix"
   services:
     - docker:27-dind
-  script:
-    - echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf
-    - nix-env -iA nixpkgs.docker
-    - nix build .#container-ci
-    - docker load < ./result
-    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-    # INFO: Check if the image tag already exists, until immutable tags are ready.
-    - |
-      if docker pull $IMAGE:$IMAGE_TAG; then
-        echo "Image with tag $IMAGE_TAG already exists. Failing the pipeline."
-        exit 1
-      fi
-    - docker image tag banterbus-dev:latest $IMAGE:latest
-    - docker image tag banterbus-dev:latest $IMAGE:$IMAGE_TAG
-    - docker push $CI_REGISTRY_IMAGE/ci:latest
-    - docker push $IMAGE:$IMAGE_TAG
+  extends:
+    - .docker
 
 
 download:dependency:
@@ -146,22 +157,14 @@ publish:dev:docker:
   stage: build
   needs: []
   variables:
-    DOCKER_HOST: tcp://docker:2375
-    DOCKER_DRIVER: overlay2
-    DOCKER_TLS_CERTDIR: ""
+    IMAGE: $CI_REGISTRY_IMAGE:dev
+    FLAKE_TARGET: container
+    LOCAL_IMAGE: banterbus
+    IMMUTABLE: "false"
   rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-  services:
-    - docker:27-dind
-  script:
-    - echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf
-    - nix-env -iA nixpkgs.docker
-    - nix develop -c task build:dev
-    - nix build .#container
-    - docker load < ./result
-    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-    - docker image tag banterbus:latest $CI_REGISTRY_IMAGE:dev
-    - docker push $CI_REGISTRY_IMAGE:dev
+  extends:
+    - .docker
 
 deploy:dev:
   stage: deploy
