ci: speed up format job

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -10,8 +10,6 @@ tasks:
 
   build:dev:
     desc: Build the app for development, generates all the files needed for the binary.
-    deps:
-      - generate
     cmds:
       - go build -o ./tmp/main .
 
@@ -20,29 +18,13 @@ tasks:
     cmds:
       - golangci-lint run {{.CLI_ARGS}} ./...
 
-  docker:publish:
-    desc: Build and publish the Docker image
-    deps:
-      - docker:build
-    env:
-      LOCAL_IMAGE: banterbus
-      USER: $CI_REGISTRY_USER
-      PASS: $CI_REGISTRY_PASSWORD
-      REGISTRY: $CI_REGISTRY
-      IMAGE_NAME: $CI_REGISTY_IMAGE
-      IMAGE_TAG: $CI_COMMIT_TAG
-    cmds:
-      - nix build .#container
-      - docker load < result
-      - docker login -u $USER -p $PASS $REGISTRY
-      - docker image tag $LOCAL_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
-      - docker push $IMAGE_NAME:$IMAGE_TAG
-
   format:
     desc: Runs the formatter.
+    env:
+      LOCATIONS: "./internal/ ./tests/ main.go"
     cmds:
-      - goimports -local gitlab.com/hmajid2301/banterbus -w .
-      - golines -m 120 -w .
+      - goimports -local gitlab.com/hmajid2301/banterbus -w $LOCATIONS
+      - golines -m 120 -w $LOCATIONS
 
   tests:
     desc: Runs all the tests.
@@ -78,8 +60,29 @@ tasks:
       - templ generate
       - tailwindcss -i ./static/css/tailwind.css -o ./static/css/styles.css
       - sqlc generate
+      - task: format
 
   release:
     desc: Release the CLI tool.
     cmds:
       - goreleaser release --clean --verbose
+
+  docker:publish:
+    desc: Build and publish the Docker image
+    env:
+      LOCAL_IMAGE: banterbus
+      FLAKE_TARGET: container
+      IMMUTABLE: "true"
+    cmds:
+      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+      - |
+        if [ "$IMMUTABLE" = "true" ]; then
+          if docker pull $IMAGE; then
+            echo "Image with tag $IMAGE_TAG already exists. Failing the pipeline."
+            exit 1
+          fi
+        fi
+      - nix build .#${FLAKE_TARGET}
+      - docker load < result
+      - docker image tag $LOCAL_IMAGE:latest $IMAGE
+      - docker push $IMAGE
